### ISSUE TITLE
Pesquisar sobre os conceitos de Banco de Dados Relacionais

### ISSUE THREAD

**Issue by evaldo** [evaldo/gecid#1]
- Diagrama de Entidade e Relacionamento ou DER (Entidades, Atributos e Relacionamentos)
Rafael e Wagner

- Normalização, 1a., 2a., 3a. e 4a. forma normal:
Bharbara e Biana

**Comment by evaldo** [comment]
Associação da ISSUE ao projeto de Banco de dados Relacionais

**Comment by Faelxld** [comment]
OK!

**Comment by evaldo** [comment]
[Apresentação GECID.pptx](https://github.com/evaldo/gecid/files/886741/Apresentacao.GECID.pptx)
